### ISSUE TITLE
Erro de permissionamento ao tentar clonar o projeto 

### ISSUE THREAD

**Issue by pamnovalli** [prefeiturasp/SME-Livro-Aberto-Docker#1]
Ao tentar clonar o projeto seguindo os comandos do readme tenho um erro por conta de permissionamento.

Segue um exemplo na foto.
![error_repository](https://user-images.githubusercontent.com/26384933/51980898-8b1b2c00-2478-11e9-9fdd-ea04eb9702a2.png)

**Comment by phasath** [comment]
Faltou uma atualização na documentação. Esse link é do git interno da DAPP que utilizamos para desenvolver as primeiras versões.

Foi atualizado no commit 56bb9af9b0530e5c78d1b58cc95c08bf6141eafe
